services:
  # Serviço PHP
  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    volumes:
      - ./src:/var/www
    environment:
      - MYSQL_HOST=${DB_HOST}
      - MYSQL_PORT=${DB_PORT}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}

  # Serviço Nginx
  nginx:
    build:
      context: ./.docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
      - ./logs:/var/log/nginx
    ports:
      - "8000:80"
    depends_on:
      - php

  # Serviço MariaDB
  mariadb:
    image: mariadb:latest
    volumes:
      - mariadb_data:/var/lib/mysql
      - .docker/mariadb/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"  # Alterado para evitar conflitos de porta

  # Serviço phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_PORT: ${DB_PORT}
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
